### ISSUE TITLE
 docker run issue

### ISSUE THREAD

**Issue by HeliumTang** [IBM/MAX-Image-Segmenter#46]
docker run -it -p 5000:5000 max-image-segmenter
Traceback (most recent call last):
  File "/workspace/app.py", line 17, in <module>
    from api import ModelMetadataAPI, ModelPredictAPI, ModelLabelsAPI
  File "/workspace/api/__init__.py", line 17, in <module>
    from .predict import ModelPredictAPI, ModelLabelsAPI  # noqa
  File "/workspace/api/predict.py", line 67, in <module>
    class ModelPredictAPI(PredictAPI):
  File "/workspace/api/predict.py", line 69, in ModelPredictAPI
    model_wrapper = ModelWrapper()
  File "/workspace/core/model.py", line 100, in __init__
    self.model = DeepLabModel(_MOBILE_MODEL_PATH)
  File "/workspace/core/model.py", line 60, in __init__
    graph_def.ParseFromString(f.read())
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /assets/frozen_inference_graph_mobile.pb; No such file or directory

**Comment by bdwyer2** [comment]
Hi @heliumTang can you please run `docker run -it -p 5000:5000 max-image-segmenter bash` to connect to the container then run `ls -al assets/` and post the output here?

Also have you tried pulling the container from docker hub (`docker pull codait/max-image-segmenter`)?

**Comment by ptitzler** [comment]
If you could also clarify what you did prior to running. For example, did you only clone the repo and build the Docker image or did you also train the model using your own data?

**Comment by HeliumTang** [comment]
> Hi @HeliumTang can you please run `docker run -it -p 5000:5000 max-image-segmenter bash` to connect to the container then run `ls -al assets/` and post the output here?
> 
> Also have you tried pulling the container from docker hub (`docker pull codait/max-image-segmenter`)?

Yes, I pull the container from docker hub. That's the problem.
I remove the container and rebuilt docker image follow your instruction and it works. Thanks.
You can close this issue.
